env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  # Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '{ "<js>": "always" }').
  import/extensions: [0, { <js>: "always" }]
  }
